/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CtaSection: typeof import('./src/components/landing-parts/cta-section/CtaSection.vue')['default']
    FeaturesSection: typeof import('./src/components/landing-parts/features-section/FeaturesSection.vue')['default']
    GlobalStatisticsSection: typeof import('./src/components/home/GlobalStatisticsSection.vue')['default']
    HeroSection: typeof import('./src/components/landing-parts/hero-section/HeroSection.vue')['default']
    HowWorks: typeof import('./src/components/landing-parts/how-works-section/HowWorks.vue')['default']
    IntegrationCard: typeof import('./src/components/integrations/IntegrationCard.vue')['default']
    IntegrationForm: typeof import('./src/components/integrations/IntegrationForm.vue')['default']
    IntegrationSelector: typeof import('./src/components/common/IntegrationSelector.vue')['default']
    IntegrationsSection: typeof import('./src/components/home/IntegrationsSection.vue')['default']
    IOCCard: typeof import('./src/components/common/IOCCard.vue')['default']
    IOCDetailsModal: typeof import('./src/components/common/IOCDetailsModal.vue')['default']
    IOCEmptyState: typeof import('./src/components/common/IOCEmptyState.vue')['default']
    IOCProviderHeader: typeof import('./src/components/common/IOCProviderHeader.vue')['default']
    IOCQuickActions: typeof import('./src/components/common/IOCQuickActions.vue')['default']
    IOCSearchForm: typeof import('./src/components/common/IOCSearchForm.vue')['default']
    IOCSupportedTypes: typeof import('./src/components/common/IOCSupportedTypes.vue')['default']
    NetworkVisualization: typeof import('./src/components/landing-parts/hero-section/network-visualization/NetworkVisualization.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarMain: typeof import('./src/components/sidebar/SidebarMain.vue')['default']
    StatisticsSection: typeof import('./src/components/home/StatisticsSection.vue')['default']
    StatsContainer: typeof import('./src/components/landing-parts/hero-section/stats-container/StatsContainer.vue')['default']
    TopBar: typeof import('./src/components/top-bar/TopBar.vue')['default']
  }
}
